#############################################################################
# Makefile for building: Jc_Messprogramm
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Jc_Messprogramm.pro
# Template: subdirs
# Command: E:\Programme\Qt\5.15.2\msvc2019_64\bin\qmake.exe -o Makefile Jc_Messprogramm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = E:\Programme\Qt\5.15.2\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = E:\Programme\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = E:\Programme\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-Control \
		sub-ControlCore \
		sub-Instruments \
		sub-Core \
		sub-Viewer


sub-Control-qmake_all: sub-ControlCore-qmake_all FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	cd Control\ && $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && $(MAKE) -f Makefile qmake_all
sub-Control: $(MAKEFILE) sub-ControlCore FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Control-make_first: sub-ControlCore-make_first FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Control-all: sub-ControlCore-all FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Control-clean: sub-ControlCore-clean FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Control-distclean: sub-ControlCore-distclean FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Control-install_subtargets: sub-ControlCore-install_subtargets FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Control-uninstall_subtargets: sub-ControlCore-uninstall_subtargets FORCE
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-ControlCore-qmake_all: sub-Core-qmake_all FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	cd ControlCore\ && $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && $(MAKE) -f Makefile qmake_all
sub-ControlCore: $(MAKEFILE) sub-Core FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-ControlCore-make_first: sub-Core-make_first FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-ControlCore-all: sub-Core-all FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-ControlCore-clean: sub-Core-clean FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-ControlCore-distclean: sub-Core-distclean FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-ControlCore-install_subtargets: sub-Core-install_subtargets FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-ControlCore-uninstall_subtargets: sub-Core-uninstall_subtargets FORCE
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Instruments-qmake_all:  FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	cd Instruments\ && $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && $(MAKE) -f Makefile qmake_all
sub-Instruments: $(MAKEFILE) FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Instruments-make_first: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Instruments-all: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Instruments-clean: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Instruments-distclean: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Instruments-install_subtargets: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Instruments-uninstall_subtargets: FORCE
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Core-qmake_all: sub-Instruments-qmake_all FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && $(MAKE) -f Makefile qmake_all
sub-Core: $(MAKEFILE) sub-Instruments FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Core-make_first: sub-Instruments-make_first FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Core-all: sub-Instruments-all FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Core-clean: sub-Instruments-clean FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Core-distclean: sub-Instruments-distclean FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Core-install_subtargets: sub-Instruments-install_subtargets FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Core-uninstall_subtargets: sub-Instruments-uninstall_subtargets FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Viewer-qmake_all: sub-Core-qmake_all FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	cd Viewer\ && $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && $(MAKE) -f Makefile qmake_all
sub-Viewer: $(MAKEFILE) sub-Core FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Viewer-make_first: sub-Core-make_first FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Viewer-all: sub-Core-all FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Viewer-clean: sub-Core-clean FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Viewer-distclean: sub-Core-distclean FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Viewer-install_subtargets: sub-Core-install_subtargets FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Viewer-uninstall_subtargets: sub-Core-uninstall_subtargets FORCE
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Jc_Messprogramm.pro E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qml_debug.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf \
		E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf \
		Jc_Messprogramm.pro
	$(QMAKE) -o Makefile Jc_Messprogramm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qml_debug.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf:
E:\Programme\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf:
Jc_Messprogramm.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Jc_Messprogramm.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Control-qmake_all sub-ControlCore-qmake_all sub-Instruments-qmake_all sub-Core-qmake_all sub-Viewer-qmake_all FORCE

make_first: sub-Control-make_first sub-ControlCore-make_first sub-Instruments-make_first sub-Core-make_first sub-Viewer-make_first  FORCE
all: sub-Control-all sub-ControlCore-all sub-Instruments-all sub-Core-all sub-Viewer-all  FORCE
clean: sub-Control-clean sub-ControlCore-clean sub-Instruments-clean sub-Core-clean sub-Viewer-clean  FORCE
distclean: sub-Control-distclean sub-ControlCore-distclean sub-Instruments-distclean sub-Core-distclean sub-Viewer-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Control-install_subtargets sub-ControlCore-install_subtargets sub-Instruments-install_subtargets sub-Core-install_subtargets sub-Viewer-install_subtargets FORCE
uninstall_subtargets: sub-Control-uninstall_subtargets sub-ControlCore-uninstall_subtargets sub-Instruments-uninstall_subtargets sub-Core-uninstall_subtargets sub-Viewer-uninstall_subtargets FORCE

sub-Control-debug: sub-ControlCore-debug
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-ControlCore-debug: sub-Core-debug
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Instruments-debug:
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Core-debug: sub-Instruments-debug
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Viewer-debug: sub-Core-debug
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Control-debug sub-ControlCore-debug sub-Instruments-debug sub-Core-debug sub-Viewer-debug

sub-Control-release: sub-ControlCore-release
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-ControlCore-release: sub-Core-release
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Instruments-release:
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Core-release: sub-Instruments-release
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Viewer-release: sub-Core-release
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Control-release sub-ControlCore-release sub-Instruments-release sub-Core-release sub-Viewer-release

sub-Control-check: sub-ControlCore-check
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-ControlCore-check: sub-Core-check
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Instruments-check:
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Core-check: sub-Instruments-check
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Viewer-check: sub-Core-check
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Control-check sub-ControlCore-check sub-Instruments-check sub-Core-check sub-Viewer-check

sub-Control-benchmark: sub-ControlCore-benchmark
	@if not exist Control\ mkdir Control\ & if not exist Control\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Control\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Control\Control.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-ControlCore-benchmark: sub-Core-benchmark
	@if not exist ControlCore\ mkdir ControlCore\ & if not exist ControlCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ControlCore\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\ControlCore\ControlCore.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Instruments-benchmark:
	@if not exist Instruments\ mkdir Instruments\ & if not exist Instruments\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instruments\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Instruments\Instruments.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Core-benchmark: sub-Instruments-benchmark
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Viewer-benchmark: sub-Core-benchmark
	@if not exist Viewer\ mkdir Viewer\ & if not exist Viewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Viewer\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Florian\Desktop\Code\Jc_Messprogramm\Viewer\Viewer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Control-benchmark sub-ControlCore-benchmark sub-Instruments-benchmark sub-Core-benchmark sub-Viewer-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

